name: Automatic Deployment
on: [push]
jobs:
  deployment: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3 

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Set .env file
        run: | 
          echo "REACT_APP_NEWS_API=$REACT_APP_NEWS_API" >> .env
        env:  
          REACT_APP_NEWS_API: ${{ secrets.REACT_APP_NEWS_API }}
